### ISSUE TITLE
Add new layer and recipes

### ISSUE THREAD

**Issue by MickaelDelanoe** [siemens/meta-iot2050#215]
Hello,

I would like to add a new Layer (and recipes) to the existing project.
I would like add `meta-iot-cloud` layer (https://layers.openembedded.org/layerindex/branch/krogoth/layer/meta-iot-cloud/) and a personnel recipes `python-aws-iot-devices-sdk_%.bbappend`

So, I tried to modify `kas/iot2050.yml` to add layer : 

```yml
  isar:
    url: https://github.com/ilbers/isar
    refspec: 03124cca669f50b682336a0bdf4ede5a4238e144
    layers:
      meta: meta-iot-cloud
    patches:
```

And, I updated the cloned project (v01.01.01) by:
 1. Adding a recipes `recipes-aws` in the clonned project.
 2. Adding `python-aws-iot-devices-sdk_%.bbappend` to `IMAGE_INSTALL`

But I got the error : 
```
ERROR: No recipes available for:
  /repo/recipes-aws/python/python-aws-iot-device-sdk_0.1-iot2050-debian.bbappend

Summary: There was 1 ERROR message shown, returning a non-zero exit code.
2021-11-16 09:39:11 - ERROR    - Command returned non-zero exit status 1
```

Do you know, how can I add `meta-iot-cloud` layer ?

Best Regards,
